name: cd-dev
on:
  push:
    branches: [ dev ]
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TF_DEPLOYER_DEV_ARN }}
          aws-region: eu-west-3
      - run: terraform -chdir=infra/envs/dev init && terraform -chdir=infra/envs/dev apply -auto-approve
